language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t cubexvr/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true cubexvr/react-test npm test

after_success:
    - docker build -t cubexvr/multi-client ./client
    - docker build -t cubexvr/multi-nginx ./nginx
    - docker build -t cubexvr/multi-server ./server
    - docker build -t cubexvr/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push cubexvr/multi-client
    - docker push cubexvr/multi-nginx
    - docker push cubexvr/multi-server
    - docker push cubexvr/multi-worker

    deploy:
        edge: true
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "multi-docker"
        env: "MultiDocker-env"
        bucket_name: "elasticbeanstalk-us-east-2-035983262215"
        bucket_path: "multi-docker"
        on:
            branch: master        
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY